nameOverride: prom

# Disable Default Prometheus Rules
defaultRules:
  create: false

  # Disable self monitor
  serviceMonitor:
    selfMonitor: false

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.k8s.sikademo.com # --- PROMETHEUS DOMAIN ---
    paths:
      - /

  # Allow scrapping every ServiceMonitors in every namespace
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

  # Disable self monitor
  serviceMonitor:
    selfMonitor: false

grafana:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - grafana.k8s.sikademo.com # --- GRAFANA DOMAIN ---
    paths:
      - /

  # Disable default dashboards
  defaultDashboardsEnabled: false

  # Disable self monitor
  serviceMonitor:
    selfMonitor: false

alertmanager:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - alertmanager.k8s.sikademo.com # --- ALERTMANAGER DOMAIN ---
    paths:
      - /

  # Disable self monitor
  serviceMonitor:
    selfMonitor: false

# Disable Scrapping of Kubernetes Components
kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

# Deploy CRDs manually
prometheusOperator:
  createCustomResource: false
